# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    env:
      Solution_Name: src/DarkModeForms.sln

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name
    - name: Build (Release)
      run: dotnet build $env:Solution_Name --no-restore -c Release -p:GenerateResourceUsePreserializedResources=true
    - name: Test
      run: dotnet test $env:Solution_Name --no-build -c Release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DarkModeForms-binaries
        path: |
          src/DarkModeForms/bin/Release/**
          src/Example/bin/Release/**
        if-no-files-found: error
